openapi: 3.2.0
info:
  title: NEAR Protocol JSON RPC EXPERIMENTAL Split Storage Info API
  version: 1.2.11
tags:
- name: EXPERIMENTAL Split Storage Info
paths:
  /EXPERIMENTAL_split_storage_info:
    post:
      description: Contains the split storage information. More info on split storage here
      operationId: EXPERIMENTAL_split_storage_info
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JsonRpcRequest_for_EXPERIMENTAL_split_storage_info'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonRpcResponse_for_RpcSplitStorageInfoResponse_and_RpcSplitStorageInfoError'
      tags:
      - EXPERIMENTAL Split Storage Info
      summary: EXPERIMENTAL split storage info
      x-summary-source: derived
components:
  schemas:
    JsonRpcRequest_for_EXPERIMENTAL_split_storage_info:
      properties:
        id:
          type: string
        jsonrpc:
          type: string
        method:
          enum:
          - EXPERIMENTAL_split_storage_info
          type: string
        params:
          $ref: '#/components/schemas/RpcSplitStorageInfoRequest'
      required:
      - jsonrpc
      - id
      - params
      - method
      title: JsonRpcRequest_for_EXPERIMENTAL_split_storage_info
      type: object
    RpcRequestValidationErrorKind:
      oneOf:
      - properties:
          info:
            properties:
              method_name:
                type: string
            required:
            - method_name
            type: object
          name:
            enum:
            - METHOD_NOT_FOUND
            type: string
        required:
        - name
        - info
        type: object
      - properties:
          info:
            properties:
              error_message:
                type: string
            required:
            - error_message
            type: object
          name:
            enum:
            - PARSE_ERROR
            type: string
        required:
        - name
        - info
        type: object
    RpcSplitStorageInfoRequest:
      title: RpcSplitStorageInfoRequest
      type: object
    JsonRpcResponse_for_RpcSplitStorageInfoResponse_and_RpcSplitStorageInfoError:
      oneOf:
      - properties:
          result:
            $ref: '#/components/schemas/RpcSplitStorageInfoResponse'
        required:
        - result
        type: object
      - properties:
          error:
            $ref: '#/components/schemas/ErrorWrapper_for_RpcSplitStorageInfoError'
        required:
        - error
        type: object
      properties:
        id:
          type: string
        jsonrpc:
          type: string
      required:
      - jsonrpc
      - id
      title: JsonRpcResponse_for_RpcSplitStorageInfoResponse_and_RpcSplitStorageInfoError
      type: object
    ErrorWrapper_for_RpcSplitStorageInfoError:
      oneOf:
      - properties:
          cause:
            $ref: '#/components/schemas/RpcRequestValidationErrorKind'
          name:
            enum:
            - REQUEST_VALIDATION_ERROR
            type: string
        required:
        - name
        - cause
        type: object
      - properties:
          cause:
            $ref: '#/components/schemas/RpcSplitStorageInfoError'
          name:
            enum:
            - HANDLER_ERROR
            type: string
        required:
        - name
        - cause
        type: object
      - properties:
          cause:
            $ref: '#/components/schemas/InternalError'
          name:
            enum:
            - INTERNAL_ERROR
            type: string
        required:
        - name
        - cause
        type: object
    RpcSplitStorageInfoError:
      oneOf:
      - properties:
          info:
            properties:
              error_message:
                type: string
            required:
            - error_message
            type: object
          name:
            enum:
            - INTERNAL_ERROR
            type: string
        required:
        - name
        - info
        type: object
    RpcSplitStorageInfoResponse:
      description: Contains the split storage information.
      properties:
        cold_head_height:
          format: uint64
          minimum: 0
          type:
          - integer
          - 'null'
        final_head_height:
          format: uint64
          minimum: 0
          type:
          - integer
          - 'null'
        head_height:
          format: uint64
          minimum: 0
          type:
          - integer
          - 'null'
        hot_db_kind:
          type:
          - string
          - 'null'
      type: object
    InternalError:
      oneOf:
      - properties:
          info:
            properties:
              error_message:
                type: string
            required:
            - error_message
            type: object
          name:
            enum:
            - INTERNAL_ERROR
            type: string
        required:
        - name
        - info
        type: object
