openapi: 3.2.0
info:
  description: NearBlocks REST API for the NEAR Protocol block explorer. Provides endpoints to access blockchain data including accounts, transactions, blocks, tokens, NFTs, and staking.
  title: NearBlocks Explorer Legacy / Charts API
  version: 1.0.0
servers:
- description: Mainnet
  url: https://api.nearblocks.io
- description: Testnet
  url: https://api-testnet.nearblocks.io
tags:
- description: Deprecated.
  name: Legacy / Charts
paths:
  /v1/charts:
    get:
      summary: Get charts data
      tags:
      - Legacy / Charts
      responses:
        '200':
          description: Success response
      operationId: getV1Charts
      x-operation-id-source: derived
  /v1/charts/latest:
    get:
      summary: Get latest charts data
      tags:
      - Legacy / Charts
      responses:
        '200':
          description: Success response
      operationId: getV1ChartsLatest
      x-operation-id-source: derived
  /v1/charts/tps:
    get:
      summary: Get txns per second by shards chart data
      tags:
      - Legacy / Charts
      responses:
        '200':
          description: Success response
      operationId: getV1ChartsTps
      x-operation-id-source: derived
components:
  securitySchemes:
    BearerAuth:
      scheme: bearer
      type: http
